# Generated by Django 5.1.1 on 2024-10-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='version_dossier',
            field=models.CharField(default='v1', max_length=10),
        ),
    ]
